<?php

namespace App\Models\OpenCart;

use App\Models\OpenCart\Attributes\Table;

#[Table('oc_order', connection: 'opencart', primaryKey: 'order_id', incrementing: true, timestamps: true, createdAt: 'date_added', updatedAt: 'date_modified')]
class Order extends OpenCartModel
{
    protected $fillable = [
        'order_id',
        'yaorder_id',
        'invoice_no',
        'invoice_prefix',
        'store_id',
        'store_name',
        'store_url',
        'customer_id',
        'customer_group_id',
        'firstname',
        'lastname',
        'email',
        'telephone',
        'fax',
        'payment_firstname',
        'payment_lastname',
        'payment_company',
        'payment_company_id',
        'payment_tax_id',
        'payment_address_1',
        'payment_address_2',
        'payment_city',
        'payment_postcode',
        'payment_country',
        'payment_country_id',
        'payment_zone',
        'payment_zone_id',
        'payment_address_format',
        'payment_method',
        'payment_code',
        'shipping_firstname',
        'shipping_lastname',
        'shipping_company',
        'shipping_address_1',
        'shipping_address_2',
        'shipping_city',
        'shipping_postcode',
        'shipping_country',
        'shipping_country_id',
        'shipping_zone',
        'shipping_zone_id',
        'shipping_address_format',
        'shipping_method',
        'shipping_code',
        'comment',
        'total',
        'order_status_id',
        'affiliate_id',
        'commission',
        'language_id',
        'currency_id',
        'currency_code',
        'currency_value',
        'ip',
        'forwarded_ip',
        'user_agent',
        'accept_language',
        'date_added',
        'date_modified',
        'SP_start_date',
        'SP_next_date',
    ];

    protected $casts = [
        'order_id' => 'integer',
        'yaorder_id' => 'integer',
        'invoice_no' => 'integer',
        'store_id' => 'integer',
        'customer_id' => 'integer',
        'customer_group_id' => 'integer',
        'payment_country_id' => 'integer',
        'payment_zone_id' => 'integer',
        'shipping_country_id' => 'integer',
        'shipping_zone_id' => 'integer',
        'total' => 'float',
        'order_status_id' => 'integer',
        'affiliate_id' => 'integer',
        'commission' => 'float',
        'language_id' => 'integer',
        'currency_id' => 'integer',
        'currency_value' => 'float',
    ];
}
