<?php

namespace App\Models\OpenCart;

use App\Models\OpenCart\Attributes\Table;

#[Table('oc_suppler', connection: 'opencart', primaryKey: 'form_id', incrementing: true, timestamps: false)]
class Suppler extends OpenCartModel
{
    protected $fillable = [
        'form_id',
        'suppler_id',
        'name',
        'main',
        'sort_order',
        'rate',
        'ratep',
        'ratek',
        'cod',
        'item',
        'cat',
        'qu',
        'price',
        'descrip',
        'pic_ext',
        'manuf',
        'warranty',
        'ad',
        'status',
        'my_cat',
        'my_qu',
        'my_price',
        'my_descrip',
        'my_manuf',
        'my_mark',
        'weight',
        'length',
        'width',
        'height',
        'parent',
        'hide',
        'newphoto',
        'my_photo',
        'cheap',
        'addopt',
        'addseo',
        'related',
        'updte',
        'pmanuf',
        'upattr',
        'upopt',
        'upname',
        'myplus',
        'cprice',
        'minus',
        'chcode',
        'importseo',
        'sorder',
        'spec',
        'upurl',
        'ref',
        'addattr',
        'exsame',
        'sku2',
        'parss',
        'points',
        'places',
        'parsi',
        'pointi',
        'placei',
        'parsc',
        'pointc',
        'placec',
        'parsp',
        'pointp',
        'placep',
        'parsd',
        'pointd',
        'placed',
        'parsm',
        'pointm',
        'placem',
        'parsk',
        'parsq',
        'pointq',
        'placeq',
        'bprice',
        'kmenu',
        'catcreate',
        'stay',
        'joen',
        'off',
        'umanuf',
        'onn',
        'refer',
        'disc',
        'newurl',
        'upc',
        'ean',
        'mpn',
        'ddata',
        'bonus',
        'ddesc',
        'qu_discount',
        'plusopt',
        'idcat',
        't_ref',
        'termin',
        't_status',
        'onoff',
        'zero',
        'metka',
        'jopt',
        'optsku',
        'newproduct',
        'opt_prices',
        'opt_fotos',
        'ref1',
        't_ref1',
        'usd',
        'serie',
        'sleep',
        'ffile',
        'subfolder',
        'rprice',
        'delimiter',
        'skuprefix',
    ];

    protected $casts = [
        'form_id' => 'integer',
        'suppler_id' => 'integer',
        'main' => 'integer',
        'sort_order' => 'integer',
        'rate' => 'float',
        'ratep' => 'float',
        'ratek' => 'float',
        'status' => 'integer',
        'my_cat' => 'integer',
        'my_price' => 'integer',
    ];
}
